# -*- coding: utf-8 -*-
{
    'name': "INTEGRACION FENICIO",
    'summary': """INTEGRACION FENICIO""",
    'description': """INTEGRACION FENICIO""",
    'category': 'Localization',
    'version': '17.0.0.0',
    'depends': ['base', 'sale', 'sale_management', 'account', 'stock', 'product_brand', 'website_sale', 'contacts'],
    'data': [
        'security/ir.model.access.csv',
        'views/product_attribute_views.xml',
        'views/product_template_views.xml',
        'views/product_product_easy_form.xml',
        'views/account_payment_term_views.xml',
        'views/account_payment_views.xml',
        'views/sale_views.xml',
        'views/guia_talles_view.xml',
        'views/stock_location.xml',
        'views/product_brand_view.xml',
        'views/product_public_category_view.xml',
        'data/data.xml',
        'data/payments_diaries.xml',
        'views/res_partner_view.xml',
    ],
    'license': 'LGPL-3',
}
